default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.2.0/24

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.pidoorbell: debug
    homeassistant.setup: debug
    zeroconf: info
    paho.mqtt.client: info
    homeassistant.components.mqtt.client: info
